import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className={`antialiased min-h-full flex flex-col`}>
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
